#pragma kernel CSMain

RWTexture2D<float4> Result;
Texture2D<float4> InputTex;

int width;
int height;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    int x = id.x;
    int y = id.y;

    if (x <= 0 || x >= width - 1 || y <= 0 || y >= height - 1)
    {
        Result[id.xy] = float4(0, 0, 0, 1);
        return;
    }

    float3 c  = InputTex[int2(x, y)].rgb;
    float3 cx = InputTex[int2(x + 1, y)].rgb - InputTex[int2(x - 1, y)].rgb;
    float3 cy = InputTex[int2(x, y + 1)].rgb - InputTex[int2(x, y - 1)].rgb;

    float edge = length(cx) + length(cy);

    Result[int2(x, y)] = float4(edge.xxx, 1.0);
}
