#pragma kernel MoveParticle

struct Particle
{
    float3 position;
    float3 direction;

    float3 flockHeading;
    float3 flockCentre;
    float3 avoidanceHeading;
    int numFlockmates;
};

RWStructuredBuffer<Particle> Particles;
int numParticles;
float viewRadius;
float avoidRadius;

[numthreads(10, 1, 1)]
void MoveParticle (uint3 id : SV_DispatchThreadID)
{
   
    for (int i = 0; i < numParticles; i++)
    {
        if (id.x != i)
        {
            Particle currentParticle = Particles[i];
            float3 distance = currentParticle.position - Particles[id.x].position;

            //Get 
            float distanceMagnetude = distance.x * distance.x + distance.y * distance.y + distance.z * distance.z;
            
            if (distanceMagnetude < viewRadius * viewRadius)
            {
                Particles[id.x].numFlockmates += 1;
                Particles[id.x].flockHeading += currentParticle.direction;
                Particles[id.x].flockCentre += currentParticle.position;

                if (distanceMagnetude < avoidRadius * avoidRadius)
                {
                    Particles[id.x].avoidanceHeading -= distance / distanceMagnetude;
                }
            }
        }
    }
}
