// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;


[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    float2 uv = float2(id.x / 512.0, id.y / 512.0);

    float r = uv.x;
    float g = uv.y;
    float b = 0.5;

    Result[id.xy] = float4(r, g, b, 1.0);
}
